# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# 因为我是yarn,如果npm就直接使用npm

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn build --if-present
      env:
        CI: true
    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
        # Private Key
        SSH_PRIVATE_KEY: ${{ secrets.ALIYUN }}
        # Remote host
        REMOTE_HOST: "47.56.13.69"
        # Remote user
        REMOTE_USER: "root"
        # Remote port
        REMOTE_PORT: 80
        # Source directory
        SOURCE: "public/"
        # Target directory
        TARGET: "/www/wwwroot/sineava.top/"
        # Arguments to pass to rsync
        ARGS: "-rltgoDzvO --delete"
